### ISSUE TITLE
引入组件老是说模块为未install

### ISSUE THREAD

**Issue by AlexYY0** [jacques33/vue-horizontal-calendar#1]
如题

**Comment by jacques33** [comment]
抱歉，組件打包出現了問題，我明日更新npm包，解決問題了給你回復郵件




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"AlexYY0"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月6日(星期五) 晚上6:38
收件人:&nbsp;"jacques33/vue-horizontal-calendar"<vue-horizontal-calendar@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[jacques33/vue-horizontal-calendar] 引入组件老是说模块为未install (#1)




如题

**Comment by jacques33** [comment]
你好，之前由于打包的问题，导致插件引入报错；
现在最新版本 0.7.11 已经修复此问题，可以正常使用。
如后续有任何问题或建议，欢迎给我发邮件，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"AlexYY0"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月6日(星期五) 晚上6:38
收件人:&nbsp;"jacques33/vue-horizontal-calendar"<vue-horizontal-calendar@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[jacques33/vue-horizontal-calendar] 引入组件老是说模块为未install (#1)




如题
