### ISSUE TITLE
_c error

### ISSUE THREAD

**Issue by erqiu-sj** [jacques33/vue-horizontal-calendar#17]
在我使用vite+vue3的环境中，use了该包，放在对应的组件位置上时出现了报错，请问知道这是怎么回事吗？
![6A88A20EFFAFD274862F23F4EA472D42](https://user-images.githubusercontent.com/58790073/117407365-049c0180-af41-11eb-945d-28375165bb9f.png)
![B033259355EAEA7301891007BD8D52D9](https://user-images.githubusercontent.com/58790073/117407506-3c0aae00-af41-11eb-9f2f-7752c81285a1.png)
![D3F0BBADAA39AA2064C25732668AA307](https://user-images.githubusercontent.com/58790073/117407516-4036cb80-af41-11eb-8247-f7694c0fc1ab.png)
![A967FF914DFABBAC4FA19C59590863A0](https://user-images.githubusercontent.com/58790073/117407526-4331bc00-af41-11eb-90d0-06b246d40ff8.png)

**Comment by jacques33** [comment]
最后一行，你注册全局组件的话，直接 app.use(HorizontalCalendar)就好了，不需要挂载；
你那个mount是什么方法？要么是 $mount ……
总之不需要后面那一串，直接use就好
