### ISSUE TITLE
ReferenceError window is not defined

### ISSUE THREAD

**Issue by nawras-albaghdadi** [jacques33/vue-horizontal-calendar#25]
Hi, 
steps :  
1-c `import VueHorizontalCalendar from 'vue-horizontal-calendar'`
2- `export default {
  components: {
    VueHorizontalCalendar
  },
  `
  add it to the template
3-   `  <VueHorizontalCalendar lang="en" />`

 mac os
project is nuxt.js /vuejs
when refreshing the page it gives an error in the file `node_modules/vue-horizontal-calendar/lib/vue-horizontal-calendar.umd.min.js`

"ReferenceError
window is not defined"

**Comment by nawras-albaghdadi** [comment]
also the package installed using npm has only the lib folder

**Comment by jacques33** [comment]
cause Nuxt.js is server-side rendering，there has no Window Object.
you can fixed this problem with modify nuxt.js configuration，you'll get the answer in nuxt api documentation
