### ISSUE TITLE
Vue 3: Cannot read property 'parentNode' of null

### ISSUE THREAD

**Issue by jannikbuscha** [jacques33/vue-horizontal-calendar#29]
Hi, when I want to use the library in a Vue 3 Typescript environment I get this error:
![image](https://user-images.githubusercontent.com/74017697/127414449-14c2d67c-dfa4-45c4-9ce5-8e645be4690a.png)

![image](https://user-images.githubusercontent.com/74017697/127414514-a8b2e6c7-e0f0-43a5-9ce7-ede35712cfca.png)

**Comment by jannikbuscha** [comment]
Maybe that fixes the error:
https://github.com/probil/vue-moveable/issues/190

**Comment by jacques33** [comment]
> Maybe that fixes the error:
> [probil/vue-moveable#190](https://github.com/probil/vue-moveable/issues/190)

I‘am sorry to tell you that the plugin unsurport Vue3.x

**Comment by jannikbuscha** [comment]
it is also not planned by you to bring the framework to vue 3? because vue 3 is now becoming the standard

**Comment by jacques33** [comment]
It's hard to be compatible vue2.x and vue3.x , or i need to start a new project for vue3.
unfortunately I‘m so busy on my work that i don't have much time to do it.
You can download the source code, just copy the 'HorizontalCalendar.vue' file to your own project, avoid referencing it from NPM, I guess it works.
