### ISSUE TITLE
Customising the text content inside the picker

### ISSUE THREAD

**Issue by balasivagnanam** [jacques33/vue-horizontal-calendar#38]
Thanks a lot for this nice library.

It  will great if we are customise the format of display inside the selection boxes

E.g
3 words for day instead of 2
Showing month date and day instead of day and date only.

**Comment by jacques33** [comment]
sorry to so late ro reply u.
I've upgrade the plugin today，add new scope slot default, to custom the date block content or style.
the lastest version is 1.0.0, and the doc is also updated.

**Comment by mindlens** [comment]
Thank you. Will check it out. Will be highly helpful. Thank you again
