### ISSUE TITLE
Multi Language Support

### ISSUE THREAD

**Issue by dhruvvarde** [jacques33/vue-horizontal-calendar#4]
Currently, there is an option of selecting either of two languages, Chinese or English.
Can it also support Portuguese or any other language?

**Comment by jacques33** [comment]
I'm so sorry to say that it can't,cause I know nothing about Portuguese or any other languages.
I suggest u can download the source code, then you can modify the revelant part code. It'll be very simple.
there is only one code change is required, at /src/components/HorizentalCalendar.vue,&nbsp; under methods part, the function name is 'getWeekName'.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dhruv Varde"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月17日(星期三) 凌晨0:29
收件人:&nbsp;"jacques33/vue-horizontal-calendar"<vue-horizontal-calendar@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[jacques33/vue-horizontal-calendar] Multi Language Support (#4)





 
Currently, there is an option of selecting either of two languages, Chinese or Engish.
 Can it also support Portuguese or any other language?
