### ISSUE TITLE
手机上无法兼容

### ISSUE THREAD

**Issue by igouz** [jacques33/vue-horizontal-calendar#6]
手机上无法兼容

**Comment by jacques33** [comment]
额，这个是PC端的组件哦，没考虑移动端的兼容性。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jacques33/vue-horizontal-calendar"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月26日(星期天) 晚上6:00
收件人:&nbsp;"jacques33/vue-horizontal-calendar"<vue-horizontal-calendar@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[jacques33/vue-horizontal-calendar] 手机上无法兼容 (#6)





 
手机上无法兼容

**Comment by gannianyi** [comment]
可考虑移动端兼容吗？

**Comment by jacques33** [comment]
要支持移动端，整个组件的UI相关以及部分属性配置功能代码，都需要重写；
本人暂时没有精力去做这件事情，抱歉
